config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'opinions#index', as: :root
  get '/user/:id', to: 'users#show', as: :user
  get '/signup', to: 'users#new', as: :signup
  post '/new_user', to: 'users#create', as: :new_user
  delete '/logout', to: 'users#destroy', as: :logout
  get '/signin', to: 'users#signin', as: :sign_in
  post '/signin', to: 'users#login', as: :signin
  post '/create_opinion', to: 'opinions#create', as: :new_opinion
  get '/follow/:followed_id', to: 'friendships#create', as: :follow
  delete '/:followed_id', to: 'friendships#destroy', as: :unfollow
  get '/retweet/:opinion_id', to: 'retweets#create', as: :retweet
  delete '/unretweet/:opinion_id', to: 'retweets#destroy', as: :unretweet
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :Follower, foreign_key: 'Followerid', class_name: 'User'
  belongs_to :Followed, foreign_key: 'Followedid', class_name: 'User'

  def self.find_friend_to_unfollow(sender_id, receiver_id)
    Friendship.where(Followerid: sender_id).where(Followedid: receiver_id)[0]
  end
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :Author, foreign_key: 'AuthorId', class_name: 'User'
  validates :Text, presence: true, length: { maximum: 260 }
  has_many :retweets, foreign_key: 'OpinionId', class_name: 'Retweet'

  def self.get_user_retweets(id)
    retweets_arr = []
    Retweet.where(UserId: id).each do |retweet|
      retweets_arr.push(retweet.OpinionId)
    end
    retweets_arr
  end

  def self.get_users_posts(id)
    retweets_arr = Opinion.get_user_retweets(id)
    Opinion.where(AuthorId: id).or(where(id: retweets_arr)).distinct.order(created_at: :desc)
  end

  def self.get_related_opinions(id)
    arr = [id]
    followed = Friendship.where(Followerid: id)
    followed.each { |follow| arr.push(follow.Followedid) } if followed.any?
    retweets_arr = Opinion.get_user_retweets(id)
    Opinion.where(AuthorId: arr).or(where(id: retweets_arr)).distinct.eager_load(:retweets).order(created_at: :desc)
  end
end

app/models/retweet.rb
class Retweet < ApplicationRecord
  belongs_to :user, foreign_key: 'UserId', class_name: 'User'
  belongs_to :opinion, foreign_key: 'OpinionId', class_name: 'Opinion'

  def self.find_user_retweet(user_id, opinion_id)
    Retweet.where(UserId: user_id).where(OpinionId: opinion_id)[0]
  end

  def self.retweets_for_post(opinion_id)
    Retweet.where(OpinionId: opinion_id).size
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :opinions, foreign_key: 'AuthorId', class_name: 'Opinion'
  has_many :followed, foreign_key: 'Followerid', class_name: 'Friendship'
  has_many :followers, foreign_key: 'Followedid', class_name: 'Friendship'
  has_many :retweets, foreign_key: 'UserId', class_name: 'Retweet'
  before_save :downcase_username
  mount_uploader :Photo, ImageUploader
  mount_uploader :CoverImage, ImageUploader
  validates :Username, presence: true, length: { maximum: 15 },
                       uniqueness: { case_sensitive: false }
  validates :Fullname, presence: true

  def remember
    token = User.new_token
    update_attribute(:remember_token, User.digest(token))
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def self.find_friends(id)
    arr = [id]
    followed = Friendship.where(Followerid: id).order(created_at: :desc)

    followed.each { |follow| arr.push(follow.Followedid) } if followed.any?
    User.where.not(id: arr).order(created_at: :desc).limit(5)
  end

  def self.user_followers(id, curr_user_id)
    Friendship.where(Followedid: id).where.not(Followerid: curr_user_id).order(created_at: :desc).limit(5)
  end

  private

  def downcase_username
    self.Username = self.Username.downcase
  end

  def generate_token
    token = User.new_token
    self.remember_token = User.digest(token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include UsersHelper

  def log_in(user)
    user.remember
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def authorize
    redirect_to sign_in_path unless logged_in?
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    Friendship.create(Followerid: current_user.id, Followedid: params[:followed_id])
    redirect_to user_path(params[:followed_id])
  end

  def destroy
    @friendship = Friendship.find_friend_to_unfollow(current_user.id, params[:followed_id])
    @friendship.destroy
    redirect_to user_path(params[:followed_id])
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :authorize, only: [:index]

  def index
    @opinion = Opinion.new
    @opinions = Opinion.get_related_opinions(current_user.id)
    @users = User.find_friends(current_user.id)
  end

  def create
    @opinion = Opinion.new(opinion_params)
    @opinion.AuthorId = current_user.id
    @users = User.find_friends(current_user.id)
    @opinions = Opinion.get_related_opinions(current_user.id)

    if @opinion.save
      redirect_to root_path
    else
      render 'index'
    end
  end

  private

  def opinion_params
    params.require(:opinion).permit(:Text)
  end
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
  def create
    Retweet.create(OpinionId: params[:opinion_id], UserId: current_user.id)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @retweet = Retweet.find_user_retweet(current_user.id, params[:opinion_id])
    @retweet.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @user.reload

      log_in @user
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @opinions = Opinion.get_users_posts(params[:id])
    @followers = User.user_followers(params[:id], current_user.id)
  end

  def signin; end

  def login
    user = User.find_by(Username: params[:user][:Username])

    if user
      log_in user
      redirect_to root_path
    else
      flash.now[:notice] = 'User not found'
      render 'signin'
    end
  end

  def destroy
    sign_out if logged_in?
    redirect_to sign_in_path
  end

  private

  def user_params
    params.require(:user).permit(:Username, :Fullname, :Photo, :CoverImage)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/retweets_helper.rb
module RetweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def logged_in?
    !current_user.nil?
  end

  attr_writer :current_user

  def current_user
    @current_user ||= User.find_by(remember_token: cookies[:remember_token])
  end

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.Username.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.Fullname, class: 'gravatar')
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CapstoneProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= stylesheet_link_tag 'application', '//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/opinions/_header_nav.html.erb
<nav class="topnav">
  <%= image_tag 'twitter-512.png' %>
  <ul>
    <li><i class="material-icons">edit</i></li>
    <li><i class="material-icons">email</i></li>
    <li><i class="material-icons">search</i></li>
    <li><i class="material-icons">settings</i></li>
  </ul>
</nav>

app/views/opinions/_side_nav.html.erb
  
<div class="sideNav">
  <div class="sm-box">
    <div class="hero-section">
      <% if current_user[:Photo].nil? %>
        <%= gravatar_for current_user, size: 50 %>
      <% else %>
        <%= image_tag current_user.Photo.thumb.url %>
      <% end %>
      <p class="p-text"><%= current_user.Fullname.upcase %></p>
    </div>
  </div>
  <div class="ff-box">
    <div class="side-following right-border">
      <div class="stats">
        <p class="stat-no"><%= current_user.followed.count %></p>
        <p class="stat-name">Following</p>
      </div>
    </div>
    <div class="side-following">
      <div class="stats">
        <p class="stat-no"><%= current_user.followers.count %></p>
        <p class="stat-name">Followers</p>
      </div>
    </div>
  </div>
  <div class="links">
    <div class="home-link">
      <i class="material-icons">home</i>
      <%= link_to 'HOME', root_path %>
    </div>
    <div class="home-link">
      <i class="material-icons">person</i>
      <%= link_to 'PROFILE', user_path(current_user.id) %>
    </div>
    <div class="home-link">
      <i class="material-icons">power_settings_new</i>
      <%= link_to 'LOGOUT', logout_path, method: :delete %>
    </div>
  </div>
</div>

app/views/opinions/index.html.erb
<div class="container">
  <%= render 'side_nav' %>
  <main class="main-section">
    <%= render 'header_nav' %>
    <div class="wrapper">
      <section class="big-section">
        <div class="b-bottom">
          <div class="tab">
            <div class="tab-p">
              <p>TWEETS</p>
            </div>
          </div>
        </div>
        <div class="tweets">
          <div class="new-tweet">
            <p>TWEET SOMETHING</p>
            <%= form_for @opinion, url: new_opinion_path  do |f| %>
              <%= f.text_area :Text, placeholder: "Compose new tweet" %>
              <% if @opinion.errors[:Text][0]  %>
                <p class="error">* <%= @opinion.errors[:Text][0] %></p>
              <% end %>
              <%= f.submit "Tweet" %>
            <% end %>
          </div>
          <% if @opinions.any? %>
            <div class="my-related-tweets">
              <% @opinions.each do |opinion| %>
                <div class="opinion">
                  <% if opinion.Author[:Photo].nil? %>
                    <%= gravatar_for opinion.Author, size: 50 %>
                  <% else %>
                    <%= image_tag opinion.Author.Photo.thumb.url %>
                  <% end %>
                  <div class="opinion-user">
                    <h4><%= opinion.Author.Fullname %></h4>
                    <p><%= opinion.Text %></p>
                  </div>
                </div>
                <div class="retweet-section">
                  <% if opinion.retweets.any? { |retweet| retweet.UserId == current_user.id }%>
                    <%= link_to unretweet_path(opinion), method: :delete, class: 'user' do %>
                      <i class="material-icons blue">autorenew</i>
                    <% end %>
                  <% else %>
                    <%= link_to retweet_path(opinion), class: 'user' do %>
                      <i class="material-icons grey">autorenew</i>
                    <% end %>
                  <% end %>
                  <% if opinion.retweets.any? %>
                    <p><%= "#{pluralize(opinion.retweets.count, 'retweet')}" %></p>
                  <% end %>
                </div>
              <% end  %>
            </div>
          <% end %>
        </div>
      </section>
      <aside class="side-bar">
        <div class="followers-hero">
          <p class="followers-hero-p">WHO TO FOLLOW</p>
          <i class="material-icons">sync</i>
        </div>
        <div class="find-friends">
          <% @users.each do |user| %>
            <%= link_to user_path(user), class: 'user' do %>
              <% unless user[:Photo].nil? %>
                <%= image_tag user.Photo.thumb.url %>
              <% else %>
                <%= gravatar_for user, size: 50 %>
              <% end %>
              <h6><%= user.Fullname %></h6>
            <% end %>
          <% end %>
        </div>
      </aside>
    </div>
  </main>
</div>

app/views/users/_nav.html.erb
<div class="nav-links">
  <ul>
    <li><%= link_to 'Sign up', signup_path %></li>
    <li><%= link_to 'Sign in', sign_in_path %></li>
  </ul>
</div>

app/views/users/new.html.erb
<%= render 'nav' %>
<div class="form">
  <%= form_for @user, url: new_user_path do |f| %>
    <div class="image">
      <%= image_tag("twitter.png",  alt: "Twitter Icon", class: "twitter-logo") %>
    </div>
    <div class="field">
      <%= f.text_field :Fullname, placeholder: "Full Name" %>
      <% if @user.errors[:Fullname][0]  %>
        <p class="error">* <%= @user.errors[:Fullname][0] %></p>
      <% end %>
    </div>
    <div class="field">
      <%= f.text_field :Username, placeholder: "Username" %>
      <% if @user.errors[:Username][0] %>
        <p class="error">* <%= @user.errors[:Username][0] %></p>
      <% end %>
    </div>
    <div class= "field">
      <%= f.label :Photo %>
      <%= f.file_field :Photo %>
      <% if @user.errors[:Photo][0] %>
        <p class="error"><%= @user.errors[:Photo][0] %></p>
      <% end %>
    </div>
    <div class="field">
      <%= f.label :CoverImage %>
      <%= f.file_field :CoverImage %>
      <% if @user.errors[:CoverImage][0]%>
        <p class="error"><%= @user.errors[:CoverImage][0] %></p>
      <% end %>
    </div>
    <%= f.submit "Create User" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <%= render 'opinions/side_nav' %>
  <main class="main-section">
    <%= render 'opinions/header_nav' %>
    <div class="wrapper">
      <section class="big-section">
        <% unless @user[:CoverImage].nil? %>
          <div class="cover-img" 
            style="background-image: url('<%= @user.CoverImage.standard.url %>'); 
            background-color: inherit;">
          </div>
        <% else %>
          <div class="cover-img">
          </div>
        <% end %>
        <div class="b-bottom">
          <div class="tab">
            <div class="tab-p">
              <p>TWEETS</p>
            </div>
          </div>
        </div>
        <div class="tweets">
          <% if @opinions.any? %>
            <div class="my-related-tweets">
              <% @opinions.each do |opinion| %>
                <div class="opinion">
                  <% if opinion.Author[:Photo].nil? %>
                    <%= gravatar_for opinion.Author, size: 50 %>
                  <% else %>
                    <%= image_tag opinion.Author.Photo.thumb.url %>
                  <% end %>
                  <div class="opinion-user">
                    <h4><%= opinion.Author.Fullname %></h4>
                    <p><%= opinion.Text %></p>
                  </div>
                </div>
                <div class="retweet-section">
                  <% if opinion.retweets.any? { |retweet| retweet.UserId == current_user.id }%>
                    <%= link_to unretweet_path(opinion), method: :delete, class: 'user' do %>
                      <i class="material-icons blue">autorenew</i>
                    <% end %>
                  <% else %>
                    <%= link_to retweet_path(opinion), class: 'user' do %>
                      <i class="material-icons grey">autorenew</i>
                    <% end %>
                  <% end %>
                  <% if opinion.retweets.any? %>
                    <p><%= "#{pluralize(opinion.retweets.count, 'retweet')}" %></p>
                  <% end %>
                </div>
              <% end  %>
            </div>
          <% end %>
        </div>
      </section>
      <aside class="side-bar">
        <div class="user-container">
          <div class="user-detailed-info" style="<%= "width: 30%;" if current_user.id == @user.id %>">
            <% unless current_user.id == @user.id %>
              <% if current_user.followed.any? { |person| person.Followedid == @user.id }%>
                <%= link_to unfollow_path(@user), method: :delete, class: "material-icons" do %>
                  <i class="material-icons">remove_circle_outline</i>
                <% end %>
              <%else%>
                <%= link_to follow_path(@user), class: "material-icons" do %>
                  <i class="material-icons">add_circle_outline</i>
                <% end %>
              <% end %>
            <% end %>
            <% unless @user[:Photo].nil? %>
              <%= image_tag @user.Photo.standard.url %>
            <% else %>
              <%= gravatar_for @user, size: 100 %>
            <% end %>
            <% unless current_user.id == @user.id %>
              <i class="material-icons">list</i>
            <% end %>
          </div>
        </div>
        <div class="user-detailed-stats">
          <h5><%= @user.Fullname.upcase %></h5>
          <p>@<%= @user.Username %></p>
        </div>
        <div class="ff-box">
          <div class="side-following right-border">
            <div class="stats">
              <p class="stat-no"><%= @opinions.count %></p>
              <p class="stat-name">Tweets</p>
            </div>
          </div>
          <div class="side-following right-border">
            <div class="stats">
              <p class="stat-no"><%= @user.followed.count %></p>
              <p class="stat-name">Following</p>
            </div>
          </div>
          <div class="side-following">
            <div class="stats">
              <p class="stat-no"><%= @user.followers.count %></p>
              <p class="stat-name">Followers</p>
            </div>
          </div>
        </div>
        <% if @followers.any? %>
          <div class="followers-hero">
            <p class="followers-hero-p">FOLLOWED BY</p>
          </div>
          <div class="find-friends">
            <% @followers.each do |follower| %>
              <div class="user">
                <% unless follower.Follower[:Photo].nil? %>
                  <%= image_tag follower.Follower.Photo.thumb.url %>
                <% else %>
                  <%= gravatar_for follower.Follower, size: 50 %>
                <% end %>
                <h6><%= follower.Follower.Fullname %></h6>
                <% if current_user.followed.any? { |person| person.Followedid == follower.Follower.id }%>
                  <%= link_to unfollow_path(follower.Follower), method: :delete, class: "material-icons" do %>
                    <i class="material-icons">remove_circle_outline</i>
                  <% end %>
                <%else%>
                  <%= link_to follow_path(follower.Follower), class: "material-icons" do %>
                    <i class="material-icons">add_circle_outline</i>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      </aside>
    </div>
  </main>
</div>

app/views/users/signin.html.erb
<%= render 'nav' %>

<div class="form">
  <%= form_for :user, url: signin_path do |f| %>
    <div class="image">
      <%= image_tag("twitter.png",  alt: "Twitter Icon", class: "twitter-logo") %>
    </div>

    <p class="error center"><%= notice %></p>

    <div class="field">
      <%= f.text_field :Username, placeholder: "Username" %>
    </div>
    <%= f.submit "Login" %>
  <% end %>
</div>